name: Build Docker Image with Kaniko

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    env:
      DOCKER_USERNAME: ${{ secrets.test.DOCKER_USERNAME }}
      DOCKER_ACCESS_TOKEN: ${{ secrets.test.DOCKER_ACCESS_TOKEN }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Hub token
        run: echo "DOCKER_ACCESS_TOKEN=${DOCKER_ACCESS_TOKEN}" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker run -v $(pwd):/workspace \
            -e DOCKER_CONFIG=/kaniko-secrets/docker_token \
            gcr.io/kaniko-project/executor \
            --context=/workspace \
            --dockerfile=/workspace/app/Dockerfile \
            --destination=iamgovindthakur/my-kaniko-image:1.0 \
            --insecure \
            --skip-tls-verify \
            --skip-tls-verify-pull \
            --insecure-pull \
            --build-arg=DOCKER_ACCESS_TOKEN=${DOCKER_ACCESS_TOKEN}
